# Generated by Django 4.0.4 on 2022-06-10 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0003_alter_artist_excerpt'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='slug',
            field=models.SlugField(default=None, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='slug',
            field=models.SlugField(default=None, help_text='Part of the URL on the main Track page. Must me unique.', max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='type',
            field=models.CharField(choices=[('Vocal', 'Vocal'), ('Non-Vocal', 'Non-Vocal')], db_index=True, default='Vocal', max_length=16),
        ),
    ]
