# Generated by Django 4.0.4 on 2022-06-11 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0004_artist_slug_alter_track_slug_alter_track_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='birth_location',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='type',
            field=models.CharField(blank=True, choices=[('Composer', 'Composer'), ('Singer', 'Singer')], max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='voice_type',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='slug',
            field=models.SlugField(default=None, editable=False, max_length=255, null=True, unique=True),
        ),
    ]
