# Generated by Django 4.0.4 on 2022-06-11 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
        ('tracks', '0005_artist_bio_artist_birth_location_artist_birthday_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='images',
            field=models.ManyToManyField(to='images.s3image'),
        ),
    ]
