# Generated by Django 4.0.4 on 2022-06-11 10:20

from django.db import migrations, models
import django.db.models.deletion
import tools.upload


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0006_artist_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='images',
        ),
        migrations.CreateModel(
            name='ArtistImage',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated date')),
                ('s3_source', models.ImageField(blank=True, max_length=512, null=True, upload_to=tools.upload.ModifyUpload('s3_all'))),
                ('s3_source_width', models.IntegerField(editable=False, null=True)),
                ('s3_source_height', models.IntegerField(editable=False, null=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artist_images', to='tracks.artist')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
