# Generated by Django 4.0.4 on 2022-06-11 11:42

from django.db import migrations, models
import tools.upload


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0007_remove_artist_images_artistimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistimage',
            name='s3_source',
            field=models.ImageField(max_length=512, upload_to=tools.upload.ModifyUpload('s3_all')),
        ),
        migrations.AlterField(
            model_name='track',
            name='title',
            field=models.CharField(blank=True, db_index=True, max_length=2048, null=True, verbose_name='Track title'),
        ),
    ]
