# Generated by Django 4.0.4 on 2022-06-11 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0008_alter_artistimage_s3_source_alter_track_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='hide',
            field=models.BooleanField(default=False, help_text='Temporary field, i will remove it very soon', verbose_name='Hide'),
        ),
    ]
