# Generated by Django 4.0.4 on 2022-06-11 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0009_artist_hide'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='label',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='label',
            name='founded',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='label',
            name='slug',
            field=models.SlugField(default=None, editable=False, max_length=255, null=True, unique=True),
        ),
    ]
