# Generated by Django 4.0.4 on 2022-06-11 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0010_label_country_label_description_label_founded_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='label',
            name='founded',
        ),
    ]
