# Generated by Django 4.0.4 on 2022-06-11 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0011_remove_label_founded'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='founded',
            field=models.IntegerField(blank=True, null=True, verbose_name='Year Founded'),
        ),
    ]
