# Generated by Django 4.0.4 on 2022-06-12 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0012_label_founded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='hide',
            field=models.BooleanField(db_index=True, default=False, help_text='Temporary field, i will remove it very soon', verbose_name='Hide'),
        ),
    ]
