# Generated by Django 4.0.4 on 2022-06-15 17:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tools.upload
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracks', '0014_alter_artistimage_created_alter_artistimage_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Created date')),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated date')),
                ('submitted_file', models.FileField(help_text='.mp3 file location', upload_to=tools.upload.ModifyUpload('file'), verbose_name='.MP3 File')),
                ('submitted_title', models.CharField(max_length=2048)),
                ('submitted_name', models.CharField(max_length=2048)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
