# Generated by Django 4.0.4 on 2022-06-15 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0018_alter_genre_style'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='style',
        ),
        migrations.AddField(
            model_name='style',
            name='genre',
            field=models.ManyToManyField(to='tracks.genre'),
        ),
    ]
