# Generated by Django 4.0.4 on 2022-06-15 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0020_style_picture_style_picture_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='email',
            field=models.EmailField(max_length=512, null=True),
        ),
    ]
