# Generated by Django 4.0.4 on 2022-07-02 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0022_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='email',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='file',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='name',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='title',
        ),
        migrations.AddField(
            model_name='submission',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Raw Text'),
        ),
    ]
