# Generated by Django 4.0.4 on 2022-07-02 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0023_remove_submission_email_remove_submission_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='show_new_releases',
            field=models.BooleanField(default=0),
        ),
    ]
