# Generated by Django 4.0.4 on 2022-07-04 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0024_track_show_new_releases'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='original_artist',
            field=models.CharField(blank=True, db_index=True, help_text='Contains artist field from .mp3 tag', max_length=1024, null=True, verbose_name='Artist'),
        ),
    ]
