# Generated by Django 4.0.4 on 2022-07-04 19:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0025_alter_track_original_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='profile_aliases',
            field=models.TextField(blank=True, help_text='Write every entity from a new line', null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='real_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='ArtistSite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Created date')),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated date')),
                ('source', models.CharField(choices=[('wikipedia', 'Wikipedia'), ('youtube', 'YouTube'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('twitter', 'Twitter'), ('spotify', 'Spotify'), ('itunes', 'iTunes')], db_index=True, max_length=64)),
                ('url', models.URLField()),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracks.artist')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
