# Generated by Django 4.0.4 on 2022-07-04 19:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0026_artist_profile_aliases_artist_real_name_artistsite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistsite',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artist_sites', to='tracks.artist'),
        ),
        migrations.AlterField(
            model_name='artistsite',
            name='source',
            field=models.CharField(choices=[('Wikipedia', 'Wikipedia'), ('YouTube', 'YouTube'), ('Instagram', 'Instagram'), ('Facebook', 'Facebook'), ('Twitter', 'Twitter'), ('Spotify', 'Spotify'), ('iTunes', 'iTunes')], db_index=True, max_length=64),
        ),
        migrations.CreateModel(
            name='LabelSite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Created date')),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated date')),
                ('source', models.CharField(choices=[('Wikipedia', 'Wikipedia'), ('YouTube', 'YouTube'), ('Instagram', 'Instagram'), ('Facebook', 'Facebook'), ('Twitter', 'Twitter'), ('Spotify', 'Spotify'), ('iTunes', 'iTunes')], db_index=True, max_length=64)),
                ('url', models.URLField()),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artist_sites', to='tracks.label')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
