# Generated by Django 4.0.4 on 2022-07-05 18:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0029_remove_artist_birth_location_remove_artist_birthday_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artistyoutube',
            options={'verbose_name': 'YouTube link', 'verbose_name_plural': 'YouTube links'},
        ),
        migrations.CreateModel(
            name='ArtistAlias',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Created date')),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated date')),
                ('alias', models.CharField(db_index=True, max_length=255)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artist_aliases', to='tracks.artist')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
