# Generated by Django 4.0.4 on 2022-07-05 19:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0030_alter_artistyoutube_options_artistalias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labelsite',
            name='source',
        ),
        migrations.AlterField(
            model_name='artist',
            name='contact_info',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Contact Info'),
        ),
        migrations.AlterField(
            model_name='label',
            name='contact_info',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Contact Info'),
        ),
        migrations.AlterField(
            model_name='label',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Profile'),
        ),
        migrations.CreateModel(
            name='LabelYoutube',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Created date')),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated date')),
                ('url', models.URLField()),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='label_youtubes', to='tracks.label')),
            ],
            options={
                'verbose_name': 'YouTube link',
                'verbose_name_plural': 'YouTube links',
            },
        ),
        migrations.CreateModel(
            name='LabelSocial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Created date')),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated date')),
                ('source', models.CharField(choices=[('Facebook', 'Facebook'), ('Instagram', 'Instagram'), ('Twitter', 'Twitter'), ('VK', 'VK')], db_index=True, max_length=64, verbose_name='Social Network')),
                ('url', models.URLField()),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='label_social', to='tracks.label')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LabelMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Created date')),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated date')),
                ('source', models.CharField(choices=[('Spotify', 'Spotify'), ('Apple Music', 'Apple Music')], db_index=True, max_length=64, verbose_name='Service')),
                ('url', models.URLField()),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='label_medias', to='tracks.label')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
