# Generated by Django 4.0.4 on 2022-07-05 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0031_remove_labelsite_source_alter_artist_contact_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='beatport',
            field=models.URLField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='discogs',
            field=models.URLField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='label',
            name='beatport',
            field=models.URLField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='label',
            name='discogs',
            field=models.URLField(blank=True, db_index=True, null=True),
        ),
    ]
