# Generated by Django 4.0.4 on 2022-07-20 05:46

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0033_artist_is_wikipedia_artist_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='original_artist_search_vector',
            field=django.contrib.postgres.search.SearchVectorField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='title_search_vector',
            field=django.contrib.postgres.search.SearchVectorField(editable=False, null=True),
        ),
        migrations.AddIndex(
            model_name='track',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title_search_vector'], name='tracks_trac_title_s_4d7c9e_gin'),
        ),
        migrations.AddIndex(
            model_name='track',
            index=django.contrib.postgres.indexes.GinIndex(fields=['original_artist_search_vector'], name='tracks_trac_origina_bb8a58_gin'),
        ),
    ]
