# Generated by Django 4.0.4 on 2022-08-18 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0034_track_original_artist_search_vector_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='sublabel',
            field=models.ForeignKey(blank=True, help_text='Set SubLabel from current table', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracks.label'),
        ),
    ]
