# Generated by Django 4.0.4 on 2022-08-18 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0035_label_sublabel'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='birth_location',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Place of birth'),
        ),
        migrations.AddField(
            model_name='artist',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='Date of birth'),
        ),
        migrations.AddField(
            model_name='artist',
            name='daw',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='DAW'),
        ),
        migrations.AddField(
            model_name='artist',
            name='is_daw',
            field=models.BooleanField(default=False, verbose_name='DAW'),
        ),
        migrations.AddField(
            model_name='artist',
            name='living_location',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Place of living'),
        ),
    ]
