# Generated by Django 4.0.4 on 2022-08-18 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0036_artist_birth_location_artist_birthday_artist_daw_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='living_location',
        ),
        migrations.AlterField(
            model_name='artist',
            name='location',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Place of living'),
        ),
    ]
