# Generated by Django 4.0.4 on 2022-07-01 10:59

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tools.upload
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Created date')),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated date')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, default=None, max_length=255, null=True, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('excerpt', models.TextField(blank=True, null=True)),
                ('picture', models.FileField(blank=True, null=True, upload_to=tools.upload.ModifyUpload('post'))),
                ('picture_thumbnail', models.FileField(blank=True, null=True, upload_to=tools.upload.ModifyUpload('post_thumbnail'))),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
