# Generated by Django 4.0.4 on 2022-06-14 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0004_comment_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='play',
            name='created',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Created date'),
        ),
        migrations.AlterField(
            model_name='play',
            name='updated',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated date'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='created',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Created date'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='updated',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated date'),
        ),
    ]
