# Generated by Django 4.0.4 on 2022-07-01 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0005_alter_play_created_alter_play_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='play',
            name='ipv',
            field=models.CharField(max_length=16, null=True, verbose_name='IP Version'),
        ),
    ]
