# Generated by Django 4.0.4 on 2022-07-02 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0006_play_ipv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='play',
            name='ip',
            field=models.CharField(max_length=46, null=True, verbose_name='IP Address'),
        ),
    ]
