# Generated by Django 4.0.4 on 2022-07-04 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0025_alter_track_original_artist'),
        ('interactions', '0007_alter_play_ip'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackPlays',
            fields=[
            ],
            options={
                'verbose_name': 'Play',
                'verbose_name_plural': 'Plays',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('tracks.track',),
        ),
        migrations.AddField(
            model_name='comment',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tracks.artist'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tracks.track'),
        ),
    ]
