# Generated by Django 4.0.4 on 2022-07-04 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0008_trackplays_comment_artist_alter_comment_track'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentArtists',
            fields=[
            ],
            options={
                'verbose_name': 'Artist Comment',
                'verbose_name_plural': 'Artist Comments',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('interactions.comment',),
        ),
        migrations.CreateModel(
            name='CommentTracks',
            fields=[
            ],
            options={
                'verbose_name': 'Track Comment',
                'verbose_name_plural': 'Track Comments',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('interactions.comment',),
        ),
    ]
