# Generated by Django 4.0.4 on 2022-07-04 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0009_commentartists_commenttracks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentartists',
            options={'verbose_name': 'Comment/Artist', 'verbose_name_plural': 'Comments/Artist'},
        ),
        migrations.AlterModelOptions(
            name='commenttracks',
            options={'verbose_name': 'Comment/Track', 'verbose_name_plural': 'Comments/Track'},
        ),
    ]
