# Generated by Django 4.0.4 on 2022-07-06 07:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracks', '0032_artist_beatport_artist_discogs_label_beatport_and_more'),
        ('interactions', '0010_alter_commentartists_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='type',
            field=models.CharField(choices=[('track', 'Track'), ('artist', 'Artist')], db_index=True, default='', max_length=16),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Created date')),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated date')),
                ('type', models.CharField(choices=[('like', 'Like'), ('play', 'Play')], db_index=True, max_length=16)),
                ('play', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='interactions.play')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracks.track')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='interactions.vote')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
