# Generated by Django 4.0.4 on 2022-07-06 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0011_comment_type_stat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stat',
            name='type',
            field=models.CharField(choices=[('vote', 'Like'), ('play', 'Play')], db_index=True, max_length=16),
        ),
    ]
