# Generated by Django 4.0.4 on 2022-07-04 12:28

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Created date')),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated date')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, default=None, max_length=255, null=True, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('is_deletable', models.BooleanField(default=True, editable=False)),
                ('page_max_width', models.IntegerField(default=1200, help_text='In pixels. Set to 0 to disable limit.')),
                ('url_mask', models.CharField(help_text='Note: URL should contain one leading slash and no trailing slashes', max_length=1024, unique=True, verbose_name='URL')),
                ('type', models.CharField(choices=[('Text', 'Custom Text Page'), ('Frontend', 'Frontend Page'), ('Mixed', 'Mixed Page')], db_index=True, default='Text', max_length=16)),
                ('section', models.CharField(blank=True, choices=[('Main', 'Main'), ('User', 'User')], db_index=True, max_length=16, null=True)),
                ('page', models.CharField(blank=True, choices=[('HOME', 'Home'), ('ARTISTS', 'Artists'), ('ARTIST_SINGLE', 'Artist Detail'), ('LABELS', 'Labels'), ('LABEL_SINGLE', 'Label Detail'), ('TRACKS', 'Tracks'), ('TRACK_SINGLE', 'Track Detail'), ('FAVOURITES', "User's Favorites"), ('HISTORY', "User's History"), ('NEWS', 'News Detail'), ('SUBMIT', 'Offer Track'), ('UPLOAD', 'Upload Files')], db_index=True, max_length=64, null=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PageMain',
            fields=[
            ],
            options={
                'verbose_name': 'Main Menu Item',
                'verbose_name_plural': 'Main Menu Items',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('pages.page',),
        ),
        migrations.CreateModel(
            name='PageUser',
            fields=[
            ],
            options={
                'verbose_name': 'User Menu Item',
                'verbose_name_plural': 'User Menu Items',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('pages.page',),
        ),
    ]
