# Generated by Django 4.0.4 on 2022-06-09 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='browser',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_seen',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Last seen'),
        ),
        migrations.AddField(
            model_name='user',
            name='operating_system',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
