# Generated by Django 4.0.4 on 2022-06-14 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_browser_user_last_seen_user_operating_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userverificationdata',
            name='created',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Created date'),
        ),
        migrations.AlterField(
            model_name='userverificationdata',
            name='updated',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated date'),
        ),
    ]
