# Generated by Django 4.0.4 on 2022-07-01 18:59

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_userverificationdata_created_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Guest',
        ),
        migrations.CreateModel(
            name='UserOnline',
            fields=[
            ],
            options={
                'verbose_name': 'User Online',
                'verbose_name_plural': 'Users Online',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='banned_by_ip',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
