# Generated by Django 4.0.4 on 2022-07-01 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_delete_guest_useronline_user_banned_by_ip_guest'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, default='Not implemented', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='region',
            field=models.CharField(blank=True, default='Not implemented', max_length=255, null=True),
        ),
    ]
