# Generated by Django 4.0.4 on 2022-07-01 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_latitude_user_longitude_user_timezone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ipv',
            field=models.CharField(max_length=16, null=True, verbose_name='IP Version'),
        ),
    ]
