# Generated by Django 4.0.4 on 2022-07-02 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_ipv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='utc_offset',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='UTC offset'),
        ),
    ]
