# Generated by Django 4.0.4 on 2022-07-02 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_user_utc_offset'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='_password',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
