# Generated by Django 4.0.4 on 2022-07-02 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_user__password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='_password',
            new_name='_raw_password',
        ),
    ]
