# Generated by Django 4.0.4 on 2022-07-02 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_user__raw_password_alter_user_is_guest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercontactform',
            name='ip',
            field=models.CharField(max_length=46, null=True, verbose_name='IP Address'),
        ),
        migrations.AddField(
            model_name='usercontactform',
            name='ipv',
            field=models.CharField(max_length=16, null=True, verbose_name='IP Version'),
        ),
        migrations.AlterField(
            model_name='user',
            name='ip',
            field=models.CharField(max_length=46, null=True, verbose_name='IP Address'),
        ),
    ]
