# Generated by Django 4.0.4 on 2022-08-18 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_user_phpbb_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phpbb_id',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='PHPBB ID'),
        ),
    ]
