# Generated by Django 4.0.4 on 2022-09-16 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tracks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('tracks.submission',),
        ),
        migrations.CreateModel(
            name='OfferLink',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Created date')),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated date')),
                ('link', models.CharField(max_length=2048)),
                ('source', models.CharField(blank=True, choices=[('youtube', 'YouTube')], db_index=True, max_length=64, null=True)),
                ('title', models.CharField(blank=True, max_length=2048, null=True)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offers.offer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
