# Generated by Django 4.0.4 on 2022-07-02 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_offerlink_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerlink',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offers.offer'),
        ),
    ]
