# Generated by Django 4.0.4 on 2022-09-16 09:09

from django.db import migrations, models
import tools.upload


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='S3Image',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Created date')),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated date')),
                ('s3_source', models.ImageField(blank=True, max_length=512, null=True, upload_to=tools.upload.ModifyUpload('s3_all'))),
                ('s3_source_width', models.IntegerField(editable=False, null=True)),
                ('s3_source_height', models.IntegerField(editable=False, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
