# Generated by Django 4.0.4 on 2022-06-11 09:41

from django.db import migrations, models
import tools.upload


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='S3Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s3_source', models.ImageField(blank=True, max_length=512, null=True, upload_to=tools.upload.ModifyUpload('s3_all'))),
                ('s3_source_width', models.IntegerField(editable=False, null=True)),
                ('s3_source_height', models.IntegerField(editable=False, null=True)),
            ],
        ),
    ]
