# Generated by Django 4.0.4 on 2022-06-14 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_s3image_created_s3image_updated_alter_s3image_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='s3image',
            name='created',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Created date'),
        ),
        migrations.AlterField(
            model_name='s3image',
            name='updated',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated date'),
        ),
    ]
